### ISSUE TITLE
Compile Minic 0.82 on macOS with UCI & TEST_SUITE enabled

### ISSUE THREAD

**Issue by twoplan** [tryingsomestuff/Minic#4]
Just tried to compile Minic version 0.82 on my mac. Used following command and got a working binary, but without UCI support.

**g++ -O3 minic.cc -o minic -flto -march=native -std=c++14 -DNDEBUG**
```
./minic 
# This is Minic version dev
# Warn  2019-07-27 16:41:02-865: ARG key not given, debugMode
# Info  2019-07-27 16:41:02-866: From config file, debugMode : 0
# Warn  2019-07-27 16:41:02-866: ARG key not given, debugFile
# Info  2019-07-27 16:41:02-866: From config file, debugFile : minic.debug
# Warn  2019-07-27 16:41:02-866: ARG key not given, book
# Info  2019-07-27 16:41:02-866: From config file, book : 1
# Warn  2019-07-27 16:41:02-866: ARG key not given, bookFile
# Info  2019-07-27 16:41:02-866: From config file, bookFile : book.bin
# Warn  2019-07-27 16:41:02-866: ARG key not given, ttSizeMb
# Info  2019-07-27 16:41:02-866: From config file, ttSizeMb : 1024
# Warn  2019-07-27 16:41:02-866: ARG key not given, threads
# Info  2019-07-27 16:41:02-866: From config file, threads : 1
# Warn  2019-07-27 16:41:02-866: ARG key not given, mateFinder
# Info  2019-07-27 16:41:02-866: From config file, mateFinder : 0
# Warn  2019-07-27 16:41:02-866: ARG key not given, fullXboardOutput
# Info  2019-07-27 16:41:02-866: From config file, fullXboardOutput : 1
# Warn  2019-07-27 16:41:02-866: ARG key not given, level
# Info  2019-07-27 16:41:02-866: From config file, level : 10
# Info  2019-07-27 16:41:02-866: Init hash
# Info  2019-07-27 16:41:02-866: Init TT
# Info  2019-07-27 16:41:02-866: Bucket size 48
# Info  2019-07-27 16:41:03-350: Size of TT 768Mb
# Info  2019-07-27 16:41:03-350: Init lmr
# Info  2019-07-27 16:41:03-351: Init mvv-lva
# Info  2019-07-27 16:41:03-351: Init mask
# Info  2019-07-27 16:41:03-351: KPK init
# Info  2019-07-27 16:41:03-366: Material hash total : 944784
# Info  2019-07-27 16:41:03-371: Using 1 threads
# Warn  2019-07-27 16:41:03-371: book file book.bin not found, cannot load book
# Info  2019-07-27 16:41:03-371: Init timeman
# Info  2019-07-27 16:41:03-371: Init xboard
# Info  2019-07-27 16:41:03-371: Init COM
# Info  2019-07-27 16:41:03-371: Reading fen rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
# Info  2019-07-27 16:41:03-371: No en passant square given
# Info  2019-07-27 16:41:03-503: Starting XBoard main loop
feature ping=1 setboard=1 edit=0 colors=0 usermove=1 memory=0 sigint=0 sigterm=0 otim=0 time=1 nps=0 draw=0 playother=0 myname="Minic dev"
feature done=1
# Info  2019-07-27 16:41:03-503: XBoard: mode  2
# Info  2019-07-27 16:41:03-503: XBoard: stm   0
# Info  2019-07-27 16:41:03-503: XBoard: state 3
uci
# Info  2019-07-27 16:41:07-476: Received command : uci
# Info  2019-07-27 16:41:07-476: stopping previous search
# Error 2019-07-27 16:41:07-477: Trying to read bad move, invalid from square uc i
@todo:: backtrace
# Info  2019-07-27 16:41:07-477: Xboard does not know this command "uci"
# Info  2019-07-27 16:41:07-477: XBoard: mode  2
# Info  2019-07-27 16:41:07-477: XBoard: stm   0
# Info  2019-07-27 16:41:07-477: XBoard: state 3
```
Enabling UCI support didn't compile here.

g++ -O3 minic.cc -o minic -flto -march=native -std=c++14 -DNDEBUG **-DWITH_UCI**
```
In file included from minic.cc:3777:
./Add-On/uci.cc:142:41: error: too few arguments to function call, at least
      argument 'st' must be specified
                        COM::thinkAsync();
                        ~~~~~~~~~~~~~~~ ^
minic.cc:3490:5: note: 'thinkAsync' declared here
    void thinkAsync(State st, TimeType forcedMs = -1) { // fork a futur...
    ^
1 error generated.
```

Also option **WITH_TEST_SUITE** didn't compile.

g++ -O3 minic.cc -o minic -flto -march=native -std=c++14 -DNDEBUG **-DWITH_TEST_SUITE**
```
In file included from minic.cc:3793:
./Add-On/testSuite.cc:153:36: error: no member named 'searchSync' in
      'ThreadPool'
            ThreadPool::instance().searchSync(d);
            ~~~~~~~~~~~~~~~~~~~~~~ ^
minic.cc:185:86: error: call to function 'operator<<' that is neither visible in
      the template definition nor found by argument-dependent lookup
  ...T> Logging::LogIt & operator<<(T const & value) { _buffer << value; retu...
                                                               ^
./Add-On/testSuite.cc:164:76: note: in instantiation of function template
      specialization
      'Logging::LogIt::operator<<<std::__1::vector<std::__1::basic_string<char>,
      std::__1::allocator<std::__1::basic_string<char> > > >' requested here
  ...Logging::LogIt(Logging::logInfo) << "Best move should be " << extP.bestM...
                                                                ^
./Add-On/testSuite.cc:9:16: note: 'operator<<' should be declared prior to the
      call site
std::ostream & operator<<(std::ostream & os, const std::vector<T> &v){
               ^
2 errors generated.
```
Is my command line wrong, or are these macOS issues?

**Comment by tryingsomestuff** [comment]
Thanks, I ll fix that quick.Le 27 juil. 2019 17:03, Max <notifications@github.com> a écrit :Just tried to compile Minic version 0.82 on my mac. Used following command and got a working binary, but without UCI support.
g++ -O3 minic.cc -o minic -flto -march=native -std=c++14 -DNDEBUG
./minic 
# This is Minic version dev
# Warn  2019-07-27 16:41:02-865: ARG key not given, debugMode
# Info  2019-07-27 16:41:02-866: From config file, debugMode : 0
# Warn  2019-07-27 16:41:02-866: ARG key not given, debugFile
# Info  2019-07-27 16:41:02-866: From config file, debugFile : minic.debug
# Warn  2019-07-27 16:41:02-866: ARG key not given, book
# Info  2019-07-27 16:41:02-866: From config file, book : 1
# Warn  2019-07-27 16:41:02-866: ARG key not given, bookFile
# Info  2019-07-27 16:41:02-866: From config file, bookFile : book.bin
# Warn  2019-07-27 16:41:02-866: ARG key not given, ttSizeMb
# Info  2019-07-27 16:41:02-866: From config file, ttSizeMb : 1024
# Warn  2019-07-27 16:41:02-866: ARG key not given, threads
# Info  2019-07-27 16:41:02-866: From config file, threads : 1
# Warn  2019-07-27 16:41:02-866: ARG key not given, mateFinder
# Info  2019-07-27 16:41:02-866: From config file, mateFinder : 0
# Warn  2019-07-27 16:41:02-866: ARG key not given, fullXboardOutput
# Info  2019-07-27 16:41:02-866: From config file, fullXboardOutput : 1
# Warn  2019-07-27 16:41:02-866: ARG key not given, level
# Info  2019-07-27 16:41:02-866: From config file, level : 10
# Info  2019-07-27 16:41:02-866: Init hash
# Info  2019-07-27 16:41:02-866: Init TT
# Info  2019-07-27 16:41:02-866: Bucket size 48
# Info  2019-07-27 16:41:03-350: Size of TT 768Mb
# Info  2019-07-27 16:41:03-350: Init lmr
# Info  2019-07-27 16:41:03-351: Init mvv-lva
# Info  2019-07-27 16:41:03-351: Init mask
# Info  2019-07-27 16:41:03-351: KPK init
# Info  2019-07-27 16:41:03-366: Material hash total : 944784
# Info  2019-07-27 16:41:03-371: Using 1 threads
# Warn  2019-07-27 16:41:03-371: book file book.bin not found, cannot load book
# Info  2019-07-27 16:41:03-371: Init timeman
# Info  2019-07-27 16:41:03-371: Init xboard
# Info  2019-07-27 16:41:03-371: Init COM
# Info  2019-07-27 16:41:03-371: Reading fen rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
# Info  2019-07-27 16:41:03-371: No en passant square given
# Info  2019-07-27 16:41:03-503: Starting XBoard main loop
feature ping=1 setboard=1 edit=0 colors=0 usermove=1 memory=0 sigint=0 sigterm=0 otim=0 time=1 nps=0 draw=0 playother=0 myname="Minic dev"
feature done=1
# Info  2019-07-27 16:41:03-503: XBoard: mode  2
# Info  2019-07-27 16:41:03-503: XBoard: stm   0
# Info  2019-07-27 16:41:03-503: XBoard: state 3
uci
# Info  2019-07-27 16:41:07-476: Received command : uci
# Info  2019-07-27 16:41:07-476: stopping previous search
# Error 2019-07-27 16:41:07-477: Trying to read bad move, invalid from square uc i
@todo:: backtrace
# Info  2019-07-27 16:41:07-477: Xboard does not know this command "uci"
# Info  2019-07-27 16:41:07-477: XBoard: mode  2
# Info  2019-07-27 16:41:07-477: XBoard: stm   0
# Info  2019-07-27 16:41:07-477: XBoard: state 3

Enabling UCI support didn't compile here.
g++ -O3 minic.cc -o minic -flto -march=native -std=c++14 -DNDEBUG -DWITH_UCI
In file included from minic.cc:3777:
./Add-On/uci.cc:142:41: error: too few arguments to function call, at least
      argument 'st' must be specified
                        COM::thinkAsync();
                        ~~~~~~~~~~~~~~~ ^
minic.cc:3490:5: note: 'thinkAsync' declared here
    void thinkAsync(State st, TimeType forcedMs = -1) { // fork a futur...
    ^
1 error generated.

Also option WITH_TEST_SUITE didn't compile.
g++ -O3 minic.cc -o minic -flto -march=native -std=c++14 -DNDEBUG -DWITH_TEST_SUITE
In file included from minic.cc:3793:
./Add-On/testSuite.cc:153:36: error: no member named 'searchSync' in
      'ThreadPool'
            ThreadPool::instance().searchSync(d);
            ~~~~~~~~~~~~~~~~~~~~~~ ^
minic.cc:185:86: error: call to function 'operator<<' that is neither visible in
      the template definition nor found by argument-dependent lookup
  ...T> Logging::LogIt & operator<<(T const & value) { _buffer << value; retu...
                                                               ^
./Add-On/testSuite.cc:164:76: note: in instantiation of function template
      specialization
      'Logging::LogIt::operator<<<std::__1::vector<std::__1::basic_string<char>,
      std::__1::allocator<std::__1::basic_string<char> > > >' requested here
  ...Logging::LogIt(Logging::logInfo) << "Best move should be " << extP.bestM...
                                                                ^
./Add-On/testSuite.cc:9:16: note: 'operator<<' should be declared prior to the
      call site
std::ostream & operator<<(std::ostream & os, const std::vector<T> &v){
               ^
2 errors generated.

Is my command line wrong, or are these macOS issues?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by tryingsomestuff** [comment]
Thanks, it's fixed now. Please not that UCI support is only partial. If you can, you shall still prefer XBOARD for now.

**Comment by twoplan** [comment]
Great, -DWITH_UCI now works!

But -DWITH_TEST_SUITE still generates a compile error.

BTW, the download size of minic-master with 160MB is hefty.
```
g++ -O3 minic.cc -o minic -flto -march=native -mtune=native -m64 -std=c++14 -DNDEBUG -DWITH_TEST_SUITE

minic.cc:186:86: error: call to function 'operator<<' that is neither visible in
      the template definition nor found by argument-dependent lookup
  ...T> Logging::LogIt & operator<<(T const & value) { _buffer << value; retu...
                                                               ^
./Add-On/testSuite.cc:192:66: note: in instantiation of function template
      specialization
      'Logging::LogIt::operator<<<std::__1::vector<std::__1::basic_string<char>,
      std::__1::allocator<std::__1::basic_string<char> > > >' requested here
                Logging::LogIt(Logging::logInfo) << "Mea style " << extP...
                                                                 ^
./Add-On/testSuite.cc:9:16: note: 'operator<<' should be declared prior to the
      call site
std::ostream & operator<<(std::ostream & os, const std::vector<T> &v){
               ^
1 error generated.

```

**Comment by tryingsomestuff** [comment]
Yes you're not the first to make the remark about size ... This is because of Dist folder ...
I think I shall stop deliver unofficial release and clean up the repo. The fun of Minic is being small ... hundred of Mb of executable is not ... ;-)

The last error is corrected (the dirty way ...), i'll do better soon.

Thank again for testing !
